config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'messages/show'
  get 'messages/new'
  get 'messages/create'
  get 'messages/edit'
  get 'messages/update'
  get 'messages/destroy'

  resources :messages

  root 'messages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @messages =Message.find(params[:id])
  end

  def new
  end

  def create
    @messages = Message.new(message_params)
 
    if @messages.save
    redirect_to messages_path
    # redirect_to @messages 
    else
      render 'new'
    end
  end
# Message
  def edit
    @messages =Message.find(params[:id])
  end

  def update
    @messages = Message.find(params[:id])
 
  if @messages.update(message_params)
    redirect_to @messages
  else
    render 'edit'
  end
  end

  def destroy
    @messages =Message.find(params[:id])
    @messages.destroy  
  
    redirect_to messages_path
  end

  private
  def message_params
    params.require(:messages).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
    
  </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with scope: :messages, url: messages_path, local: true do |form| %>
 
 <div class="input-group mb-3">
    <%= form.text_field :message , :class => 'form-control' %>
    
    <div class="input-group-append">
    <%= form.submit  'send' , :class => 'btn btn-outline-primary' %>

    </div>
  </div>
 
  <p>
  </p>
<% end %>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/destroy.html.erb
<h1>Messages#destroy</h1>
<p>Find me in app/views/messages/destroy.html.erb</p>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>
<%= link_to 'Back', messages_path , {:class => 'btn btn-outline-danger'}  %>

<%= render 'form' %>

app/views/messages/index.html.erb
<h1> messages</h1>

<%= link_to 'Back', messages_path , {:class => 'btn btn-outline-danger'}  %>
 <%= link_to 'New message', new_message_path , {:class => 'btn btn-outline-success'} %>
 <br>
 <br>
<table class="table  table-bordered">
  <tr>
    <th>messages</th>
    <th colspan="3">Actions</th>
  </tr>
 
  <% @messages.each do |messag| %>
    <tr>
      <td><%= messag.message %></td>
      <td><%= link_to 'Show', message_path(messag) %></td>
      <td><%= link_to 'Edit', edit_message_path(messag) %></td>
      <td><%= link_to 'Destroy', message_path(messag),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
              </td>
    </tr>
  <% end %>
</table>
<%= render 'form' %>

app/views/messages/new.html.erb
<h1>New Message</h1>
<%= link_to 'Back', messages_path , {:class => 'btn btn-outline-danger'}  %>
 
<%= render 'form' %>

app/views/messages/show.html.erb
<p>
  <strong>Message:</strong>
  <%= @messages.message %>
</p>
<%= link_to 'Back', messages_path %>

app/views/messages/update.html.erb
<h1>Messages#update</h1>
<p>Find me in app/views/messages/update.html.erb</p>